name: Deploy
on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      GITHUB_ID: ${{ secrets.GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
      AUTH_URL: ${{ secrets.AUTH_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install"

      - name: Build step
        run: "npm run build && (cp -r public .next/standalone/public; cp -r .next/static .next/standalone/.next/static; mv .next/standalone/server.js .next/standalone/server.cjs)"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "karlorz-sample-todo-80"
          entrypoint: "./server.cjs"
          root: ".next/standalone"
          
          
